### ISSUE TITLE
Protect against empty strings with non null string types

### ISSUE THREAD

**Issue by armincerf** [Code-Hex/graphql-codegen-typescript-validation-schema#12]
I'm somewhat new to yup so maybe I'm missing something here, but what is the reason behind generating `defined()` for non null types rather than `required()`?

I only ask because `required()` will prevent empty strings (which is what I want for all non null string types)

Or if that's not a good reason to change it, is there any way of telling the generator I want `required()` for all non null strings so I don't get empty strings slipping through?

Thanks

**Comment by Code-Hex** [comment]
@armincerf Thanks for asking a question to me.

This is because it conforms to the types generated by [graphql-codegen/typescript](https://www.graphql-code-generator.com/plugins/typescript).

> what is the reason behind generating defined() for non null types rather than `required()`?

This is an example generated type by it.

```ts
export interface A {
  name: Scalars['String'];
}
```

As you know, it can handle strings, including empty characters.

Another reason is that it is not always the case that the server-side does not allow empty characters. For example, in a type-safe language such as Go, there are many cases where the decision is based on only two things: whether it is empty or whether a string has been entered. (The reason is that it's easier) In that case, create a GraphQL Schema as `String!` and send an empty character instead of null to the server-side.

---

Anyway, I can understand your question. I also initially generated `required()` as the default.

I'd like to be able to set whether empty characters are allowed by default :+1:

**Comment by Code-Hex** [comment]
@armincerf Hi 👋 

I supported a new `notAllowEmptyString` option. And just published now.

https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema/releases/tag/v0.2.0

You can use like below.

```yml
generates:
  path/to/file.ts:
    plugins:
      - graphql-codegen-validation-schema
    config:
      notAllowEmptyString: true
```

If it works as expected, please give me a star on this repository 😄

If you still have any problems, please reopen or create a new issue. Thanks.

**Comment by armincerf** [comment]
Wow thanks for the quick response and feature addition! I didn't expect such a good outcome to my question :D 

I totally understand your reason for not making it the default behaviour and the new update is working great for me.

I have starred the project and hopefully I can find time to contribute something in the future

**Comment by Code-Hex** [comment]
@armincerf Thank you so much 😄 
> I have starred the project and hopefully I can find time to contribute something in the future
