### ISSUE TITLE
[QUESTION]: nonOptionalTypename: supported?

### ISSUE THREAD

**Issue by smakinson** [Code-Hex/graphql-codegen-typescript-validation-schema#507]
Hi, Is it expected that using:

```
config: {
   ...
   nonOptionalTypename: true,
   schema: 'zod',
}
```

should prevent `.optional()` from being applied to  `__typename`? It does not seem to do this when giving it a try.

**Comment by Code-Hex** [comment]
@smakinson Could you give me more context because I'm not sure why don't you need `__typename`?

**Comment by Code-Hex** [comment]
no reply. 
Open again if you need anything else.

**Comment by btoo** [comment]
@Code-Hex for some projects, `__typename` plays a critical enough role (e.g. for discriminated unions) that [graphql-codegen allows automatically including it in the generated typescript, even if it wasnt explicitly requested in the graphql document](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript#nonoptionaltypename)

it would be nice if `typescript-validation-schema` respected / had a consistent api with this configuration

**Comment by Code-Hex** [comment]
@btoo Could you share me your some use case using typename?

**Comment by adam-becker** [comment]
I'm running into something similar on a codegen set up where this `nonOptionalTypename` would be beneficial. We have the equivalent `nonOptionalTypename` property set on our `typescript` plugin so having it here as-well would have our zod schemas properly align with the types. 

We also use __typename for discriminated unions which is why we've made it required for the types.
